---

name: lintr

on:
  # Run on any PR...
  pull_request:
  # ...or on merge to master.
  push:
    branches:
      - master

jobs:
  lintr-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
      - uses: r-lib/actions/check-r-package@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            r-lib/lintr

      - name: Install package
        run: R CMD INSTALL .

      - name: Lint files
        run: |
          Sys.setenv("LINTR_ERROR_ON_LINT" = TRUE)
          lintr::lint_package()
        shell: Rscript {0}

